version: '3.3'
services:
  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # Kafdrop
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: 'no'
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - 9000:9000
    depends_on:
      - kafka

  # Debezium Kafka Connect
  kconnect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      CONFIG_STORAGE_TOPIC: cdc_connect_configs
      OFFSET_STORAGE_TOPIC: cdc_connect_offsets
      STATUS_STORAGE_TOPIC: cdc_connect_status
      BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  # Kafka Connect UI
  kafka-connect-ui:
    image: landoop/kafka-connect-ui
    environment:
      CONNECT_URL: http://kconnect:8083 # Pointing to the Kafka Connect REST API
    ports:
      - 8000:8000
    depends_on:
      - kconnect
